// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WowBravoFunkyRap.Model;

#nullable disable

namespace WowBravoFunkyRap.Model.Migrations
{
    [DbContext(typeof(WowBravoFunkyRapDbContext))]
    [Migration("20240312160325_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.PublicityImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplaySeq")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageNameSm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageNameXs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("PublicityImageType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.ToTable("PublicityImages");
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("CreateUserId");

                    b.Property<int>("DisplaySeq")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UpdateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f904dc0-2318-4e14-878a-7ff1897a6b5f"),
                            DisplaySeq = 1,
                            Name = "宣傳圖片設定"
                        },
                        new
                        {
                            Id = new Guid("1429d0ca-c012-4467-a0ce-40c345ea7860"),
                            DisplaySeq = 2,
                            Name = "宣傳圖片查詢"
                        },
                        new
                        {
                            Id = new Guid("99fd5995-55b2-4625-8203-fe60ded5a252"),
                            DisplaySeq = 3,
                            Name = "使用者設定"
                        },
                        new
                        {
                            Id = new Guid("2196a47c-4ada-46b5-a600-0d0f7ce08349"),
                            DisplaySeq = 4,
                            Name = "使用者查詢"
                        },
                        new
                        {
                            Id = new Guid("7d8d8453-f096-4c15-942e-900fde46ad37"),
                            DisplaySeq = 5,
                            Name = "角色設定"
                        },
                        new
                        {
                            Id = new Guid("a5a53305-d5d0-49b8-9d55-d72d1da6f690"),
                            DisplaySeq = 6,
                            Name = "角色查詢"
                        });
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.RoleItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleItem");

                    b.HasData(
                        new
                        {
                            Id = "PublicityImageWrite",
                            RoleId = new Guid("8f904dc0-2318-4e14-878a-7ff1897a6b5f")
                        },
                        new
                        {
                            Id = "PublicityImageRead",
                            RoleId = new Guid("1429d0ca-c012-4467-a0ce-40c345ea7860")
                        },
                        new
                        {
                            Id = "UserWrite",
                            RoleId = new Guid("99fd5995-55b2-4625-8203-fe60ded5a252")
                        },
                        new
                        {
                            Id = "UserRead",
                            RoleId = new Guid("2196a47c-4ada-46b5-a600-0d0f7ce08349")
                        },
                        new
                        {
                            Id = "RoleWrite",
                            RoleId = new Guid("7d8d8453-f096-4c15-942e-900fde46ad37")
                        },
                        new
                        {
                            Id = "RoleRead",
                            RoleId = new Guid("a5a53305-d5d0-49b8-9d55-d72d1da6f690")
                        });
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Account")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("CreateUserId");

                    b.Property<int>("DisplaySeq")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UpdateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5077c42f-8859-48c2-97e1-5d5a2e12fb71"),
                            Account = "walter",
                            DisplaySeq = 0,
                            Email = "smickey33@gmail.com",
                            FirstName = "Walter",
                            IsEnabled = true,
                            LastName = "Chen",
                            PasswordHash = "AQAAAAIAAYagAAAAELfLsvo0htr56tBtNkkj7EjJkwlKPRlUJKp/8lbTVdhtjzd9dfx7SjtBaAp9oWHbbA=="
                        },
                        new
                        {
                            Id = new Guid("598788df-0c19-4f1e-b349-ab982a2b9981"),
                            Account = "joanne",
                            DisplaySeq = 0,
                            Email = "wwjoannems@gmail.com",
                            FirstName = "Joanne",
                            IsEnabled = true,
                            LastName = "Wang",
                            PasswordHash = "AQAAAAIAAYagAAAAELfLsvo0htr56tBtNkkj7EjJkwlKPRlUJKp/8lbTVdhtjzd9dfx7SjtBaAp9oWHbbA=="
                        });
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.UserRole", b =>
                {
                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("5077c42f-8859-48c2-97e1-5d5a2e12fb71"),
                            RoleId = new Guid("8f904dc0-2318-4e14-878a-7ff1897a6b5f")
                        },
                        new
                        {
                            UserId = new Guid("5077c42f-8859-48c2-97e1-5d5a2e12fb71"),
                            RoleId = new Guid("1429d0ca-c012-4467-a0ce-40c345ea7860")
                        },
                        new
                        {
                            UserId = new Guid("5077c42f-8859-48c2-97e1-5d5a2e12fb71"),
                            RoleId = new Guid("99fd5995-55b2-4625-8203-fe60ded5a252")
                        },
                        new
                        {
                            UserId = new Guid("5077c42f-8859-48c2-97e1-5d5a2e12fb71"),
                            RoleId = new Guid("2196a47c-4ada-46b5-a600-0d0f7ce08349")
                        },
                        new
                        {
                            UserId = new Guid("5077c42f-8859-48c2-97e1-5d5a2e12fb71"),
                            RoleId = new Guid("7d8d8453-f096-4c15-942e-900fde46ad37")
                        },
                        new
                        {
                            UserId = new Guid("5077c42f-8859-48c2-97e1-5d5a2e12fb71"),
                            RoleId = new Guid("a5a53305-d5d0-49b8-9d55-d72d1da6f690")
                        });
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.RoleItem", b =>
                {
                    b.HasOne("WowBravoFunkyRap.Model.Tables.Role", "Role")
                        .WithMany("RoleItems")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.UserRole", b =>
                {
                    b.HasOne("WowBravoFunkyRap.Model.Tables.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowBravoFunkyRap.Model.Tables.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.Role", b =>
                {
                    b.Navigation("RoleItems");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
