// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WowBravoFunkyRap.Model;

#nullable disable

namespace WowBravoFunkyRap.Model.Migrations
{
    [DbContext(typeof(WowBravoFunkyRapDbContext))]
    partial class WowBravoFunkyRapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.PublicityImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplaySeq")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageLink")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageNameSm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageNameXs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("PublicityImageType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.ToTable("PublicityImages");
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("CreateUserId");

                    b.Property<int>("DisplaySeq")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UpdateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8de9e40f-2b8a-4d7b-a8a0-19c050aed285"),
                            DisplaySeq = 1,
                            Name = "宣傳圖片設定"
                        },
                        new
                        {
                            Id = new Guid("b6955c4c-95b2-4651-ac1b-a9eeac3667f1"),
                            DisplaySeq = 2,
                            Name = "宣傳圖片查詢"
                        },
                        new
                        {
                            Id = new Guid("3c00b351-6219-45df-b422-64af224f3641"),
                            DisplaySeq = 3,
                            Name = "使用者設定"
                        },
                        new
                        {
                            Id = new Guid("30f11ae8-2673-4f56-9a61-ed34572d2655"),
                            DisplaySeq = 4,
                            Name = "使用者查詢"
                        },
                        new
                        {
                            Id = new Guid("dd5f8b00-94f9-4577-b5a5-dbabfd813a8a"),
                            DisplaySeq = 5,
                            Name = "角色設定"
                        },
                        new
                        {
                            Id = new Guid("74e10ab9-6b46-4306-b859-a41183354714"),
                            DisplaySeq = 6,
                            Name = "角色查詢"
                        });
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.RoleItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleItem");

                    b.HasData(
                        new
                        {
                            Id = "PublicityImageWrite",
                            RoleId = new Guid("8de9e40f-2b8a-4d7b-a8a0-19c050aed285")
                        },
                        new
                        {
                            Id = "PublicityImageRead",
                            RoleId = new Guid("b6955c4c-95b2-4651-ac1b-a9eeac3667f1")
                        },
                        new
                        {
                            Id = "UserWrite",
                            RoleId = new Guid("3c00b351-6219-45df-b422-64af224f3641")
                        },
                        new
                        {
                            Id = "UserRead",
                            RoleId = new Guid("30f11ae8-2673-4f56-9a61-ed34572d2655")
                        },
                        new
                        {
                            Id = "RoleWrite",
                            RoleId = new Guid("dd5f8b00-94f9-4577-b5a5-dbabfd813a8a")
                        },
                        new
                        {
                            Id = "RoleRead",
                            RoleId = new Guid("74e10ab9-6b46-4306-b859-a41183354714")
                        });
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Account")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("CreateUserId");

                    b.Property<int>("DisplaySeq")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UpdateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f50da497-7558-4b3d-b51a-b000ccd5f99a"),
                            Account = "walter",
                            DisplaySeq = 0,
                            Email = "smickey33@gmail.com",
                            FirstName = "Walter",
                            IsEnabled = true,
                            LastName = "Chen",
                            PasswordHash = "AQAAAAIAAYagAAAAELfLsvo0htr56tBtNkkj7EjJkwlKPRlUJKp/8lbTVdhtjzd9dfx7SjtBaAp9oWHbbA=="
                        },
                        new
                        {
                            Id = new Guid("52e02831-fdf2-4eb8-a7ff-314d53f010dd"),
                            Account = "joanne",
                            DisplaySeq = 0,
                            Email = "wwjoannems@gmail.com",
                            FirstName = "Joanne",
                            IsEnabled = true,
                            LastName = "Wang",
                            PasswordHash = "AQAAAAIAAYagAAAAELfLsvo0htr56tBtNkkj7EjJkwlKPRlUJKp/8lbTVdhtjzd9dfx7SjtBaAp9oWHbbA=="
                        });
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.UserRole", b =>
                {
                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("f50da497-7558-4b3d-b51a-b000ccd5f99a"),
                            RoleId = new Guid("8de9e40f-2b8a-4d7b-a8a0-19c050aed285")
                        },
                        new
                        {
                            UserId = new Guid("f50da497-7558-4b3d-b51a-b000ccd5f99a"),
                            RoleId = new Guid("b6955c4c-95b2-4651-ac1b-a9eeac3667f1")
                        },
                        new
                        {
                            UserId = new Guid("f50da497-7558-4b3d-b51a-b000ccd5f99a"),
                            RoleId = new Guid("3c00b351-6219-45df-b422-64af224f3641")
                        },
                        new
                        {
                            UserId = new Guid("f50da497-7558-4b3d-b51a-b000ccd5f99a"),
                            RoleId = new Guid("30f11ae8-2673-4f56-9a61-ed34572d2655")
                        },
                        new
                        {
                            UserId = new Guid("f50da497-7558-4b3d-b51a-b000ccd5f99a"),
                            RoleId = new Guid("dd5f8b00-94f9-4577-b5a5-dbabfd813a8a")
                        },
                        new
                        {
                            UserId = new Guid("f50da497-7558-4b3d-b51a-b000ccd5f99a"),
                            RoleId = new Guid("74e10ab9-6b46-4306-b859-a41183354714")
                        });
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.RoleItem", b =>
                {
                    b.HasOne("WowBravoFunkyRap.Model.Tables.Role", "Role")
                        .WithMany("RoleItems")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.UserRole", b =>
                {
                    b.HasOne("WowBravoFunkyRap.Model.Tables.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowBravoFunkyRap.Model.Tables.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.Role", b =>
                {
                    b.Navigation("RoleItems");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WowBravoFunkyRap.Model.Tables.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
